development:
  facebook_key: "Enter your keys here. Check Read me file to know how to get keys"
  facebook_secret: "Enter your keys here. Check Read me file to know how to get keys"

  twitter_key: "Enter your keys here. Check Read me file to know how to get keys"
  twitter_secret: "Enter your keys here. Check Read me file to know how to get keys"

  github_key: "Enter your keys here. Check Read me file to know how to get keys"
  github_secret: "Enter your keys here. Check Read me file to know how to get keys"

  linkedin_key: "Enter your keys here. Check Read me file to know how to get keys"
  linkedin_secret: "Enter your keys here. Check Read me file to know how to get keys"

  google_key: "Enter your keys here. Check Read me file to know how to get keys"
  google_secret: "Enter your keys here. Check Read me file to know how to get keys"

production:
  facebook_key: "Enter your keys here. Check Read me file to know how to get keys"
  facebook_secret: "Enter your keys here. Check Read me file to know how to get keys"

  twitter_key: "Enter your keys here. Check Read me file to know how to get keys"
  twitter_secret: "Enter your keys here. Check Read me file to know how to get keys"

  github_key: "Enter your keys here. Check Read me file to know how to get keys"
  github_secret: "Enter your keys here. Check Read me file to know how to get keys"

  linkedin_key: "Enter your keys here. Check Read me file to know how to get keys"
  linkedin_secret: "Enter your keys here. Check Read me file to know how to get keys"

  google_key: "Enter your keys here. Check Read me file to know how to get keys"
  google_secret: "Enter your keys here. Check Read me file to know how to get keys"
